config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :users

  resource :confirmation, only: [:show]


  LOCALES = /en|pt\-BR/

  scope :"(locale)", locale: LOCALES do
    resources :rooms, :users
  end

  get '/:locale' => 'home#index', locale: LOCALES
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  validates_presence_of :title, :location
  validates_length_of :description, minimum: 10, allow_blank: false

  def complete_name
    "#{title}, #{location}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    validates_presence_of :full_name, :location
    validates_length_of :bio, minimum: 30, allow_black: false

    validates :email, presence: true,
                      format: { with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/ },
                      uniqueness: true

    has_secure_password

    before_create do |user|
      user.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
      return if confirmend?

        self.confirmend_at = Time.current
        self.confirmation_token  = ''
        save!
    end

    def confirmend?
      confirmend_at.present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action do
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options
      {locale: I18n.locale}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.take(3)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/routing_with_retraces.rb
class ConfirmationsController < ApplicationController
    def show
      user = User.find_by(confirmation_token: params[:token])

      if user.present?
        user.confirm!
        redirect_to user,
          notice: I18n.t('confirmations.success')
      else
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user =  User.new(user_params)
    if @user.save
      SignupMailer.confirm_email(@user).deliver
       redirect_to @user,
                  notice: 'Cadastro criado com sucesso!'
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user,
        notice: 'Cadastro atualizado com sucesso!'
    else
      render action: :edit
    end
  end

  private

  def user_params
    params.
      require(:user).
      permit(:email, :full_name, :location, :password,
            :password_confirmation, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def error_tag(model, attribute)
        if model.errors.has_key? attribute
            content_tag(
                :div,
                model.errors[attribute].first,
                class: 'error_message'
            )
        end
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1>Quartos recem postados</h1>

  <ul>
    <% @rooms.each do |room| %>
    <li><%= link_to room.complete_name, room %></li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colchonet</title>
    <link href='http://fonts.googleapis.com/css?family=Pacifico'rel='stylesheet'type='text/css'>
 
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div id="header-wrap">
        <h1><%= link_to "colcho.net", root_path%></h1>
        <nav>
          <ul>
            <li><%= link_to t('layout.rooms'), rooms_path %></li>
            <li><%= link_to t('layout.signup'), new_user_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div id="content">
      <% if notice.present? %>
        <p id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p id="alert"><%= alert %></p>
      <% end %>


      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
  <% if room.errors.any? %>
    <div id="error_explamation">
     Ha erros no formulario, por favor verifique.
    </div>
  <% end %>

<%= form_with(model: room) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= error_tag @room, :title %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
    <%= error_tag @room, :location %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <%= error_tag @room, :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Title:</strong>
    <%= room.title %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= room.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= room.description %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1><%= t('.edit_title') %></h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to t('.show_thi_room'), @room %> |
  <%= link_to t('.back_roms'), rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1><%= t('.rom_title') %></h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to t(".back_roms"), rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explamation">
   <%= t '.general.form_error' %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <%= error_tag @user, :full_name%>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @user, :location%>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user, :email%>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @user, :password%>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= error_tag @user, :password_confirmation%>
  </p>
  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
    <%= error_tag @user, :bio%>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/users/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form'%>

<%= link_to  t('.back'), @user %>

app/views/users/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to  t('.back'), root_path %>

app/views/users/show.html.erb
<p id ="notice"><%= notice %>

<h1><%= t '.title', user_name: @user.full_name %></h1>

<ul>
    <li><%= t '.location', location: @user.location %></li>
    <li><%= t'.bio', bio: @user.bio %></li>
</ul> 

<%= link_to t('.edit'), edit_user_path(@user) %>
<%= link_to 'Home', root_path %>